Music/config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'
  # get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resource :sessions, only: [:new, :create, :destroy]

  resources :bands do 
    resources :albums, only: [:new]
  end

  resources :albums do 
    resource :tracks, only: [:new, :create, :show]
  end

  # resource :tracks
  
end

Music/app/models/album.rb
class Album < ApplicationRecord

    belongs_to :band

    has_many :tracks
end

Music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums
end

Music/app/models/track.rb
class Track < ApplicationRecord
    validates :title, :ord, :album_id, presence: true
    validates :track_type, inclusion: %w(regular bonus)
    
    belongs_to :album

    has_one :band, 
    through: :album, 
    source: :band, 
    dependent: :destroy


end

Music/app/models/user.rb
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true
    after_initialize :ensure_session_token
    
    attr_reader :password

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil unless user
        user.is_password?(password) ? user : nil
    end


end

Music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def index
        @albums = Album.all
    end

    def show 
        @album = Album.find(params[:id])
    end

    def new
        @album = Album.new
    end

    def create
        @album = Album.new(album_params)
        band = @album.band_id
        if @album.save!
            redirect_to band_url(band)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end

    end

    def edit
        @album = Album.find(params[:id])
    end

    def update 
        @album = Album.find(params[:id])
        
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
        end
    end


    private
    def album_params
        params.require(:album).permit(:title, :year, :band_id, :record_type)
    end
end

Music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?


    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

end

Music/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
    end

    def new
        @band = Band.new
    end

    def show
        @band = Band.find(params[:id])
    end

    def create
        @band = Band.new(band_params)
        if @band.save!

            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private 
    def band_params
        params.require(:band).permit(:name)
    end
end

Music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email], 
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['incorrect username or password']
      render :new
    end

  end

  def destroy
    logout
    redirect_to new_sessions_url
  end

end

Music/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  def new
    if params[:album_id]
      # debugger
      @track = Track.new(album_id: params[:album_id])
    else
      @track = Track.new
    end
  end

  def index
    @tracks = Track.where(album_id: params[:album_id])
    render album_tracks
  end

  def show
    @tracks = Track.where(album_id: params[:album_id])
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to 
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def update 
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
    end
  end

  private 
  def track_params 
    params.require(:track).permit(:title, :ord, :album_id, :track_type)
  end
end

Music/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Music/app/helpers/albums_helper.rb
module AlbumsHelper
end

Music/app/helpers/application_helper.rb
module ApplicationHelper

    def auth_token
        '<input type="hidden" name="authenticity_token" value=\"#{form_authenticity_token}\">'.html_safe
    end
end

Music/app/helpers/bands_helper.rb
module BandsHelper
end

Music/app/helpers/sessions_helper.rb
module SessionsHelper
end

Music/app/helpers/tracks_helper.rb
module TracksHelper
end

Music/app/helpers/users_helper.rb
module UsersHelper
end

Music/app/views/albums/_form.html.erb
<% if type == :new %>
    <% action_url = albums_url %>
<% else %>
    <% action_url = album_url(@album) %>
<% end %>


<form class='add_album' action="<%=action_url%>" method="post">
<% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
    <h2> Edit Album</h2>
<% else %>
    <h2> Add Album </h2>
<% end %>

<%= auth_token %>
<br>
    <label>Band Name
        <select name="album[band_id]">
        <option disabled <%= album.band_id ? "" : "selected" %> > ---Please Select---</option>
            <% Band.all.each do |band| %>
                <option value="<%= band.id %>" <%= album.band_id && album.band.name == band.name ? "selected" : "" %>> <%= band.name %> </option>
            <% end %>
        </select>
    </label>
    <br>
    <label>Album Title
        <input type="text" name="album[title]" value="<%=album.title%>">
    </label>

    <br>

     <label>Year
        <input type="text" name="album[year]" value="<%=album.year%>">
    </label>

    <br>

     <label>Album Type
        <input type="radio" name="album[record_type]" value= <%= false %> <%= "checked" if album.record_type == false %> >Live
        <input type="radio" name="album[record_type]" value= <%= true %> <%= "checked" if album.record_type == true %> >Studio
    </label>

    <br>

    <input type="submit" value="Add Album">

    </form>

Music/app/views/albums/edit.html.erb
<%= render 'form', album: @album, type: :edit %>

Music/app/views/albums/new.html.erb
<%= render 'form', album: @album, type: :new %>

Music/app/views/albums/show.html.erb
<ul> <%= @album.title %>
    <li><%=@album.year%></li>
    <li><%=@album.band_id%></li>
</ul>

Music/app/views/bands/index.html.erb
<ul>
<h3>All The Bands</h3>
<% @bands.each do |band| %>
    <ul>
    <li>
     <%= band.name %>
     <form action="<%=band_url(band)%>" method='POST'>
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Delete Band">
     </form>
     </li>
    </ul>
    <a href="<%= band_url(band) %>">Edit Band</a>
<% end %>
</ul>

Music/app/views/bands/new.html.erb
<form action="<%=bands_url%>" method="POST">
    <%= auth_token %>

    <label>Name of Band:
        <input type="text" name="band[name]" value="">
    </label>
    

    <input type="submit" value="Add Band">

</form>

Music/app/views/bands/show.html.erb
<a href="<%= bands_url %>">see all bands</a>
<h1> <%= @band.name %> </h1>
<ul>
    <h2> Albums Title </h2>
    <% @band.albums.each do |album| %>
        <li>
            <%= album.title %>
            <br>
            <br>
            <%= link_to 'Edit album!', edit_album_url(album)  %>
        </li>
        <br>
    <% end %>

</ul>

<%= link_to 'Add album!', new_band_album_url(@band)  %> <br>

Music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Music</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <header> 
  <h1> Music App </h1>

  <nav>
  <% if logged_in? %>
      <h1>Welcome <%=current_user.email%> </h1>
      <form action="<%=sessions_url%>" method="POST">
        <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
      </form>

    <% else %>
        <span><a class='buttons' href="<%= new_sessions_url %>">Sign in</a></span>
        <span><a class='buttons' href="<%= new_user_url %>">Sign up</a></span>
      <% end %>
      </nav>
    
    </header>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <p style="color: red"> <%= error %> </p>
      <% end %>
    <% end %>




  <section>
    <%= yield %>
  </section>
  </body>
</html>

Music/app/views/tracks/_form.html.erb
<% if type == :new %>
    <% action_url = album_tracks_url %>
<% else %>
    <% action_url = track_url(track) %>
<% end %>

<form action="<%=action_url%>" method="POST">
    <% if type == :edit %>
        <input type="hidden" name="_method" method="patch">
    <% end %>
    <%= auth_token %>

    <label>Track Title
        <input type="text" name="track[title]" value="<%=track.title%>">
    </label>

     <label>Album
        <select name="track[album_id]">
        <option disabled <%= track.album_id ? "" : "selected" %> > --- Please Select --- </option>
        <% Album.all.each do |album| %>
            <option value="<%= album.id %>" <%= track.album_id ? "selected" : "" %>> <%= album.title %> </option>
        <% end %>
        </select>
    </label>

    <label>Ord
        <input type="text" name="track[ord]" value="<%= track.ord %>">
    </label>

    <label>Track Type:
        <input type="radio" name="track[track_type]" value="regular" <%= "checked" if track.track_type == 'regular' %>>Regular
        <input type="radio" name="track[track_type]" value="bonus" <%= "checked" if track.track_type == 'bonus' %>>Bonus
    </label>



    <input type="submit" value="submit">

</form>

Music/app/views/tracks/edit.html.erb
<h1>Tracks#edit</h1>
<p>Find me in app/views/tracks/edit.html.erb</p>

Music/app/views/tracks/index.html.erb
<% @tracks.each do |track| %>
    <%= track.title %>
<% end %>

Music/app/views/tracks/new.html.erb
<%= render 'form', track: @track, type: :new %>

Music/app/views/tracks/show.html.erb
<ul>
<li>
<% @tracks.each do |track| %>
    <li>
    <%= track.title %>
    </li>
<% end %><
    
</li>
</ul>

Music/app/views/users/_form.html.erb
<%if type == :new %>
    <% action_url = users_url %>
    <% button_text = "sign_up" %>
<% else %>
    <% action_url = user_url(@user) %>
    <% button_text = 'edit_profile'%>
<% end %>

<h1>Welcome to the Music Site</h1>
<h2>Sign Up</h2>

<form action="<%= action_url %>" method='POST'>
<%= auth_token %>
    <% if type == :edit %>
        <input type="hidden" name="_method" value='PATCH'>
    <% end %>

    <label> Username:   
        <input type="text" name="user[email]" value= <%=@user.email%>>
    </label>

    <label> Password:   
        <input type="password" name="user[password]" value="">
    </label>

    <input type="submit" value="<%= button_text %>">

</form>

Music/app/views/users/edit.html.erb
<%= render 'form', user: @user, type: :edit %>

Music/app/views/users/new.html.erb
<%= render 'form', user: @user, type: :new %>

Music/app/views/users/show.html.erb
<h3>This is your profile</h3>

<section>
    <a class='links' href="<%= bands_url %>">See all bands</a>
</section>